(() => {
  let controlTab="users",controlUsers=[],controlRoles=[],controlSettings=null,controlAudit=[];
  const api=async(path,options={})=>{
    const response=await fetch(`${API_BASE}${path}`,{...options,headers:{"Authorization":`Bearer ${adminToken}`,...(options.headers||{})}});
    const data=await response.json();if(!response.ok)throw new Error(data.detail||"Request failed.");return data;
  };
  const renderUsers=()=>{
    const target=document.getElementById("adminControlsContent");
    target.innerHTML=`<div class="control-panel"><div class="control-heading"><div><h3>User and role management</h3><p>Engineering and QA can contribute documents; Production and Parts Quality are view-only.</p></div><button class="btn-primary" id="addAdminUser" type="button" style="padding:8px 11px;border-radius:8px">Add user</button></div><div class="user-admin-list">${controlUsers.map(user=>`<div class="user-admin-row"><div><div class="user-admin-name">${escapeHtml(user.name)}</div><div class="user-admin-meta">${escapeHtml(user.username)} · ${escapeHtml(user.department)}</div></div><select data-user-role="${escapeHtml(user.id)}">${controlRoles.map(role=>`<option ${role===user.role?"selected":""}>${escapeHtml(role)}</option>`).join("")}</select><label class="user-status-toggle"><input type="checkbox" data-user-active="${escapeHtml(user.id)}" ${user.active?"checked":""}> Active</label><button class="small-control-button" data-reset-user="${escapeHtml(user.id)}" type="button">Reset password</button></div>`).join("")}</div></div>`;
    target.querySelectorAll("[data-user-role]").forEach(select=>select.onchange=()=>updateControlUser(select.dataset.userRole,{role:select.value,department:select.value==="QA Admin"||select.value==="QA"?"QA":select.value}));
    target.querySelectorAll("[data-user-active]").forEach(input=>input.onchange=()=>updateControlUser(input.dataset.userActive,{active:input.checked}));
    target.querySelectorAll("[data-reset-user]").forEach(button=>button.onclick=async()=>{const password=prompt("Enter a new password of at least 8 characters.");if(password)await updateControlUser(button.dataset.resetUser,{password})});
    document.getElementById("addAdminUser").onclick=async()=>{
      const username=prompt("Username for the new user:");if(!username)return;
      const name=prompt("Display name:");if(!name)return;
      const role=prompt(`Role (${controlRoles.join(", ")}):`,"Engineering");if(!controlRoles.includes(role))return showToast("Choose a valid role.","error");
      const password=prompt("Temporary password (at least 8 characters):");if(!password)return;
      try{await api("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,name,role,department:role==="QA Admin"||role==="QA"?"QA":role,password})});showToast("User created.","success");await loadAdminControls()}catch(err){showToast(err.message,"error")}
    };
  };
  const updateControlUser=async(id,updates)=>{try{await api(`/api/admin/users/${encodeURIComponent(id)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(updates)});showToast("User updated.","success");await loadAdminControls()}catch(err){showToast(err.message,"error")}};
  const renderConfiguration=()=>{
    const target=document.getElementById("adminControlsContent");
    target.innerHTML=`<form class="control-panel" id="configurationForm"><div class="control-heading"><div><h3>Document structure</h3><p>These values control upload classification in both portals.</p></div></div><div class="settings-grid"><div class="settings-field"><label>Models · one per line</label><textarea id="settingModels">${escapeHtml(controlSettings.models.join("\\n"))}</textarea></div><div class="settings-field"><label>Engineering teams · one per line</label><textarea id="settingTeams">${escapeHtml(controlSettings.teams.join("\\n"))}</textarea></div><div class="settings-field span-2"><label>Document categories · one per line</label><textarea id="settingCategories">${escapeHtml(controlSettings.categories.join("\\n"))}</textarea></div></div><button class="btn-primary" style="margin-top:14px;padding:9px 13px;border-radius:8px">Save configuration</button></form>`;
    document.getElementById("configurationForm").onsubmit=event=>{event.preventDefault();saveSettings({...controlSettings,models:lines("settingModels"),teams:lines("settingTeams"),categories:lines("settingCategories")})};
  };
  const lines=id=>document.getElementById(id).value.split("\\n").map(value=>value.trim()).filter(Boolean);
  const renderApproval=async()=>{
    const docs=(await api("/api/documents")).documents||[];
    const pending=docs.filter(doc=>doc.approval_state!=="Approved");
    const target=document.getElementById("adminControlsContent");
    target.innerHTML=`<div class="control-panel" style="margin-bottom:12px"><div class="control-heading"><div><h3>Approval queue</h3><p>Engineering submissions remain unavailable to read-only teams until QA approval.</p></div></div>${pending.length?pending.map(doc=>`<div class="approval-admin-row"><div><div class="user-admin-name">${escapeHtml(doc.name)}</div><div class="user-admin-meta">${escapeHtml(doc.model)} · ${escapeHtml(doc.team)} · ${escapeHtml(doc.uploaded_by_name||"Engineering")} · ${escapeHtml(doc.approval_state)}</div></div><div><button class="small-control-button" data-document-approval="${escapeHtml(doc.id)}" data-state="Approved">Approve</button> <button class="small-control-button" data-document-approval="${escapeHtml(doc.id)}" data-state="Changes Requested">Request changes</button></div></div>`).join(""):`<div style="color:var(--app-secondary);font-size:10px">No documents are awaiting QA approval.</div>`}</div><form class="control-panel" id="retentionForm"><div class="control-heading"><div><h3>Approval rules and retention</h3><p>Control publication gates and document lifecycle policy.</p></div></div><label class="rule-row"><input id="engineeringApproval" type="checkbox" ${controlSettings.engineering_upload_requires_qa_approval?"checked":""}><span><strong>Require QA approval for Engineering uploads</strong><span>New Engineering documents remain pending until approved.</span></span></label><label class="rule-row"><input id="qaAutoApproval" type="checkbox" ${controlSettings.qa_upload_auto_approves?"checked":""}><span><strong>Automatically approve QA uploads</strong><span>QA-owned submissions publish immediately.</span></span></label><label class="rule-row"><input id="retainRevisions" type="checkbox" ${controlSettings.retain_superseded_revisions?"checked":""}><span><strong>Retain superseded revisions</strong><span>Preserve older document versions for traceability.</span></span></label><div class="settings-field" style="margin-top:12px"><label>Document retention period in days</label><input class="form-control" id="retentionDays" type="number" min="30" max="3650" value="${controlSettings.retention_days}"></div><button class="btn-primary" style="margin-top:14px;padding:9px 13px;border-radius:8px">Save policy</button></form>`;
    target.querySelectorAll("[data-document-approval]").forEach(button=>button.onclick=async()=>{try{await api(`/api/admin/documents/${encodeURIComponent(button.dataset.documentApproval)}/approval`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({approval_state:button.dataset.state,comment:"Updated from QA Admin Controls"})});showToast("Approval state updated.","success");await renderApproval()}catch(err){showToast(err.message,"error")}});
    document.getElementById("retentionForm").onsubmit=event=>{event.preventDefault();saveSettings({...controlSettings,engineering_upload_requires_qa_approval:document.getElementById("engineeringApproval").checked,qa_upload_auto_approves:document.getElementById("qaAutoApproval").checked,retain_superseded_revisions:document.getElementById("retainRevisions").checked,retention_days:Number(document.getElementById("retentionDays").value)})};
  };
  const renderAudit=()=>{
    document.getElementById("adminControlsContent").innerHTML=`<div class="control-panel"><div class="control-heading"><div><h3>Complete audit log</h3><p>Authentication, user, configuration, upload, approval, and deletion activity.</p></div></div>${controlAudit.length?controlAudit.map(item=>`<div class="audit-row"><div><div class="audit-action">${escapeHtml(item.action)}</div><div class="audit-meta">${escapeHtml(item.actor)} · ${escapeHtml(item.role)}${item.target?` · ${escapeHtml(item.target)}`:""}</div></div><div class="audit-time">${escapeHtml(new Date(item.timestamp).toLocaleString())}</div></div>`).join(""):`<div style="color:var(--app-secondary);font-size:10px">No audit activity has been recorded yet.</div>`}</div>`;
  };
  const saveSettings=async settings=>{try{const data=await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});controlSettings=data.settings;showToast("Admin settings saved.","success");renderCurrentTab()}catch(err){showToast(err.message,"error")}};
  const renderCurrentTab=()=>{if(controlTab==="users")renderUsers();if(controlTab==="configuration")renderConfiguration();if(controlTab==="approval")renderApproval();if(controlTab==="audit")renderAudit()};
  window.loadAdminControls=async()=>{
    try{
      const [usersData,settingsData,auditData]=await Promise.all([api("/api/admin/users"),api("/api/admin/settings"),api("/api/admin/audit")]);
      controlUsers=usersData.users;controlRoles=usersData.roles;controlSettings=settingsData.settings;controlAudit=auditData.audit;renderCurrentTab();
    }catch(err){document.getElementById("adminControlsContent").innerHTML=`<div class="panel" style="color:var(--danger)">${escapeHtml(err.message)}</div>`}
  };
  document.querySelectorAll("[data-control-tab]").forEach(button=>button.onclick=()=>{controlTab=button.dataset.controlTab;document.querySelectorAll("[data-control-tab]").forEach(item=>item.classList.toggle("active",item===button));renderCurrentTab()});
  document.querySelector('.nav-item[data-page="controls"]')?.addEventListener("click",loadAdminControls);
})();